services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Serializer\Normalizer\CustomNormalizer: ~
    
    SymfonyOrchestra\ViewBundle\:
        resource: '../../*'
        exclude: '../../{Exception,View,PropertyAccessor}'

    SymfonyOrchestra\ViewBundle\Serializer\Normalizer\ViewNormalizer:
        class: SymfonyOrchestra\ViewBundle\Serializer\Normalizer\ViewNormalizer
        factory: [ '@SymfonyOrchestra\ViewBundle\Serializer\Normalizer\ViewNormalizerFactory', 'create']